  # See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: csv

#fod:
#  vulnerability:
    # embed:                  # Load extra data, depending on what data you want to include in output
    #   - subEntity: details

export.dir: ${export.default.dir} # Use default export directory (unless overridden)
spring.config.activate.on-loader-plugin: fod
csv:
  output:
    stdout: false             # Disabled by default to avoid vulnerability data being exposed through log files
    header: true
    file:   ${export.dir}/${release.applicationName}-${release.releaseName}.csv
  fields:
    Date: $[vuln.introducedDate]
    Title: $[vuln.category]
    CweId: $[vuln.cwe?.replaceAll("CWE-","").substring(0,(vuln.cwe?.replaceAll("CWE-","").indexOf(",")==-1?vuln.cwe?.replaceAll("CWE-","").length():vuln.cwe?.replaceAll("CWE-","").indexOf(",")))]
    Url: "https://www.microfocus.com/en-us/products/application-security-testing/overview"
    Severity: $[vuln.severityString]
    Description: $[#abbreviate(#htmlToText(vuln.details?.summary), 15000)]
    Mitigation: $[vuln.details]
    Impact: 
    References: $[vuln.deepLink]
    Active: $[!vuln.closedStatus]
    Verified: $[vuln.bugSubmitted]
    FalsePositive: $[vuln.isSuppressed]
    Duplicate: false
