  # See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: csv

#fod:
#  vulnerability:
    # embed:                  # Load extra data, depending on what data you want to include in output
    #   - subEntity: details
fod:
  vulnerability:
    embed:                           # Load extra data, depending on what data you want to include in output
      - subEntity: all-data
export.dir: ${export.default.dir} # Use default export directory (unless overridden)
csv:
  output:
    stdout: false             # Disabled by default to avoid vulnerability data being exposed through log files
    header: true
    file:   ${export.dir}/${release.applicationName}-${release.releaseName}.csv
