export:
  from: fod
  to: json.gitlab.sast

fod:
  scopes: view-apps, view-issues, view-reports
  release:
    embed:                                          # Load static scan details if available
      - propertyName: staticScanSummary
        uri: /api/v3/scans/{currentStaticScanId}/summary
        embedIf: currentStaticScanId!=null
  vulnerability:
    filterParam: scantype:Static            # Have FoD return only static issues 
    embed:                                          # Also load details, recommendations and request-response data as required for GitLab output
      - subEntity: details
      - subEntity: recommendations

export.dir: ${CI_PROJECT_DIR:${export.default.dir}} # Unless overridden, use CI_PROJECT_DIR if defined, otherwise default export dir
json.gitlab.sast.output:
  stdout: false                                     # Disabled by default to avoid vulnerability data being exposed through log files
  pretty: true                                      # Useful for debugging, disable for optimal performance
  file:   ${export.dir}/gl-fortify-sast.json        # Output file

  spring.config.activate.on-loader-plugin: fod

json.gitlab.sast.filter.expr: vuln.scantype=='Static'
json.gitlab.sast.format:
  fields:
    schema: https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/raw/v15.0.0/dist/sast-report-format.json
    version: 15.0.0
    scan:
      start_time: $[#formatDateTime("yyyy-MM-dd'T'HH:mm:ss", release.staticScanSummary?.startedDateTime?:'1970-01-01T00:00:00')]
      end_time: $[#formatDateTime("yyyy-MM-dd'T'HH:mm:ss", release.staticScanSummary?.completedDateTime?:'1970-01-01T00:00:00')]
      status: $[release.staticAnalysisStatusTypeId==2?'success':'failure']
      type: sast
      analyzer:
        id: FoD-SAST
        name: Fortify on Demand
        url: https://www.microfocus.com/en-us/products/application-security-testing/overview
        version: SCA $[release.staticScanSummary?.staticScanSummaryDetails?.engineVersion?:'version unknown']; Rulepack $[release.staticScanSummary?.staticScanSummaryDetails?.rulePackVersion?:'version unknown']
        vendor:
          name: Fortify
      scanner:
        id: FoD-SAST
        name: Fortify on Demand
        url: https://www.microfocus.com/en-us/products/application-security-testing/overview
        version: SCA $[release.staticScanSummary?.staticScanSummaryDetails?.engineVersion?:'version unknown']; Rulepack $[release.staticScanSummary?.staticScanSummaryDetails?.rulePackVersion?:'version unknown']
        vendor: 
          name: Fortify
    vulnerabilities: $[vulnerabilityMappers.vulnerability.get()]
  vulnerabilityMappers.vulnerability.fields:
    category: sast
    confidence: $[(vuln.severityString matches "(Critical|Medium)") ? "High":"Low" ]
    description: $[#abbreviate(#htmlToText(vuln.details?.summary), 15000)]
    id: $[vuln.id]
    cwe: $[vuln.cwe?.replaceAll("CWE-","").substring(0,(vuln.cwe?.replaceAll("CWE-","").indexOf(",")==-1?vuln.cwe?.replaceAll("CWE-","").length():vuln.cwe?.replaceAll("CWE-","").indexOf(",")))]
    cve: 'N/A'
    identifiers: |-
      $[{
          {
            name:  "Instance id: "+vuln.instanceId,
            url:   vuln.deepLink,
            type:  "issueInstanceId",
            value: vuln.instanceId
          }
      }]
    location:
      file:       $[vuln.primaryLocationFull]
      start_line: $[vuln.lineNumber]
    links:
      - name: Additional issue details, including analysis trace, in Fortify on Demand
        url:  $[vuln.deepLink]
    message: $[vuln.category]
    name: $[vuln.category]
    scanner:
      id: FoD-SAST
      name: Fortify on Demand
    severity: $[vuln.severityString]
    solution: $[#abbreviate(#htmlToText(vuln.details?.explanation)+'\n\n Id:'+#htmlToText(vuln.id)+'\n\n CWE:'+#htmlToText(vuln.cwe?.replaceAll("CWE-","").substring(0,(vuln.cwe?.replaceAll("CWE-","").indexOf(",")==-1?vuln.cwe?.replaceAll("CWE-","").length():vuln.cwe?.replaceAll("CWE-","").indexOf(","))))+'\n\n'+#htmlToText(vuln.recommendations?.recommendations), 7000)]
