  # See FortifyVulnerabilityExporter documentation for FoD connection settings and release selection

export:
  from: fod
  to: csv

#fod:
#  vulnerability:
    # embed:                  # Load extra data, depending on what data you want to include in output
    #   - subEntity: details

export.dir: ${export.default.dir} # Use default export directory (unless overridden)
csv:
  output:
    stdout: false             # Disabled by default to avoid vulnerability data being exposed through log files
    header: true
    file:   ${export.dir}/${release.applicationName}-${release.releaseName}.csv
  fields:
    Date: $[vuln.introducedDate]
    Title: $[vuln.category]
    CweId: $[vuln.cwe]
    Url: https://api.emea.fortify.com/
    Severity: $[vuln.severityString]
    Description: $[vuln.category]
    Mitigation: 
    Impact: 
    References: 
    Active: $[!vuln.closedStatus]
    Verified: $[vuln.bugSubmitted]
    FalsePositive: $[vuln.isSuppressed]
    Duplicate: false
