  fields:
    source: Fortify on Demand
    scanType: $[vuln.scantype]
    id: $[vuln.id]
    issueInstanceId: $[vuln.instanceId]
    category: $[vuln.category]
    file: $[vuln.primaryLocationFull]
    line: $[vuln.lineNumber]
    cve: $[vuln.cwe]
