name: Import FoD SAST Results into GitHub Code Scanning Alerts
on: 
 workflow_dispatch:
 push:
  tags:
   - '*'
      
jobs:                                                  
  Export-FoD-To-GitHub:
    runs-on: windows-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
      # Pull SAST issues from Fortify on Demand and generate GitHub-optimized SARIF output
       - name: Export Results
         uses: fortify/gha-export-vulnerabilities@v1
         with:
          export_target: JsonRaw
          fod_base_url: "https://emea.fortify.com/"
          fod_tenant: ${{ secrets.FOD_TENANT }}
          fod_user: ${{ secrets.FOD_USER }}
          fod_password: ${{ secrets.FOD_PAT }}
          fod_release_id: ${{ secrets.FOD_RELEASE_ID }}
       - uses: actions/upload-artifact@v2
         if: always()
         with:
          name: json-files
          path: '**/*.json' 
