name: Import FoD SAST Results into GitHub Code Scanning Alerts
on: 
 workflow_dispatch:
 push:
  tags:
   - '*'
      
jobs:                                                  
  Export-FoD-To-GitHub:
    runs-on: windows-latest
    permissions:
        actions: read
        contents: read
        security-events: write
    steps:
     # Check out source code
       - name: Check Out Source Code
         uses: actions/checkout@v3
         with:
          # Fetch at least the immediate parents so that if this is a pull request then we can checkout the head.
          fetch-depth: 2
           # If this run was triggered by a pull request event, then checkout the head of the pull request instead of the merge commit.
       - run: git checkout HEAD^2
         if: ${{ github.event_name == 'pull_request' }} 
      # Pull SAST issues from Fortify on Demand and generate GitHub-optimized SARIF output
       - name: Export Results
         uses: fortify/gha-export-vulnerabilities@v1
         with:
          export_config: MyCustomExportConfig.yml
          fod_base_url: "https://emea.fortify.com/"
          fod_tenant: ${{ secrets.FOD_TENANT }}
          fod_user: ${{ secrets.FOD_USER }}
          fod_password: ${{ secrets.FOD_PAT }}
          fod_release_id: ${{ secrets.FOD_RELEASE_ID }}
       - uses: actions/upload-artifact@v2
         if: always()
         with:
          name: csv-files
          path: '**/*.csv' 
